version: '3'

env:
  IMAGE_NAME: ac-users-api
  TAG: latest

tasks:
  requirements.txt:
    desc: Generate requirements.txt file from poetry.lock
    cmds:
      - poetry export -f requirements.txt --without-hashes --output requirements.txt
    internal: True

  build:
    desc: Build docker image
    deps: ["requirements.txt"]
    cmds:
      - docker build --tag $IMAGE_NAME:$TAG .

  push:
    desc: Push latest docker image
    cmds:
      - docker tag $IMAGE_NAME:$TAG 214284003688.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$TAG
      - docker push 214284003688.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$TAG

  login:
    desc: Log into aws ECR
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 214284003688.dkr.ecr.us-east-1.amazonaws.com

  run-mongo:
    desc: Run local mongodb container
    cmds:
      - docker-compose up -d mongodb

  run:
    desc: Run the server with docker compose
    cmds:
      - docker-compose up -d

  stop:
    desc: Stop the local server
    cmds:
      - docker-compose down
